### ISSUE TITLE
cannot get Fancy Branches to work with webtrees 1.7.2

### ISSUE THREAD

**Issue by klausthaler** [JustCarmen/fancy_branches#1]
downloaded the zip, installed and activated the module.

In the Branches list I see no changes, especially nothing to click on.

In the Module administration a click on the Customize link brings me to My page.

What am I doing wrong?

**Comment by JustCarmen** [comment]
Sorry for the late reaction, but do you still have this problem? I have no idea what is causing this In my case everything works just fine and I haven't heard any other users having problems.

So I suspect there is a conflict with another custom module or a configuration or server setting. But to figure that out is not easy.

Try to disable any other custom module you might have and see if it helps. You can also e-mail me (private) a temporary user name and password with access to the configuration panel so I can have a look myself and maybe figure out what is wrong.

**Comment by klausthaler** [comment]
I am not much faster:-)

Today I took some time to play around and finally had it working as described. Presumably I just hadn't saved the module administration page and thus never had it activated.

So the problem sat before the computer.
